# Site settings
title: Wordless
description: >-
  This is my blog site, Wordless. It's hosted on a Github repo through Github Pages. This is a project being run under the VIRI.SPACE name. Check out http://viri.space to learn more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://words.viri.space" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: viri_space
github_username:  viri-space

# Build settings
markdown: kramdown
remote_theme: akiritsu/pRoJEct-NeGYa
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
style: dark


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
